# Generated by Django 4.2.11 on 2024-04-27 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="stock", name="cost_price",),
        migrations.AddField(
            model_name="productdetail",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="suppliedproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.productdetail"
            ),
        ),
    ]
