# Generated by Django 4.2.11 on 2024-04-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_stock_cost_price_productdetail_cost_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetail",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
