# Generated by Django 4.2.11 on 2024-04-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_productdetail_cost_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetail",
            name="sku",
            field=models.CharField(max_length=30),
        ),
    ]
