# Generated by Django 4.2.11 on 2024-04-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_productdetail_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetail",
            name="sku",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
