# Generated by Django 4.2.11 on 2024-04-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_productdetail_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetail",
            name="sku",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
