# Generated by Django 4.2.11 on 2024-06-07 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_productdetail_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetail",
            name="sku",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator("^([0-9]{13})|([0]{1})$")
                ],
            ),
        ),
    ]
