# Generated by Django 4.2.11 on 2024-07-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_productdetail_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
