# Generated by Django 4.2.11 on 2024-08-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_remove_groupedsizes_category_groupedsizes_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorizedSize",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.category"
                    ),
                ),
                (
                    "sizes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.groupedsizes",
                    ),
                ),
            ],
        ),
    ]
