# Generated by Django 4.2.11 on 2024-08-25 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_categorizedsize"),
    ]

    operations = [
        migrations.RemoveField(model_name="groupedsizes", name="name",),
        migrations.AddField(
            model_name="groupedsizes",
            name="category",
            field=models.ForeignKey(
                default=45,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.category",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="CategorizedSize",),
    ]
