# Generated by Django 4.2.11 on 2024-04-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
