# Generated by Django 4.2.11 on 2024-05-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_orderitem_cost_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="isvoid", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="isvoid",
            field=models.BooleanField(default=False),
        ),
    ]
